version: '3.9'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind

services:
  mariadb:
    build: ./mariadb
    init: true
    env_file: .env
    volumes: 
      - mariadb:/var/lib/mysql
    networks: 
      - inception
    restart: always
    tty: true
  wordpress:
    depends_on:
      - mariadb
    build: ./wordpress
    init: true
    env_file: .env
    volumes: 
      - wordpress:/var/www/html/wordpress
    networks: 
      - inception
    restart: always
  nginx:
    depends_on:
      - mariadb
      - wordpress
    build: ./nginx
    init: true
    env_file: .env
    volumes: 
      - wordpress:/var/www/html/wordpress
    ports:
      - 443:443
    networks: 
      - inception
    restart: always