version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception-network
    volumes :
      - ./templates:/etc/nginx/templates
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - wordpress-volume:/var/www/html
    # depends_on:
    #   - wordpress

#   wordpress:
#     #either this or the image below?
#     depends_on:
#       - db
#     build: ./wordpress
#     # image: wordpress:php7.4-fpm-alpine
#     volumes:
#       - wordpress_volume:/var/www/html
#     networks:
#       - inception-network

#   db:
#     build: ./mariadb
#     volumes:
#       - db_volume:/var/lib/mysql
#     networks:
#       - inception-network

# volumes:
#   wordpress_volume:
#     name:
#       wordpress-volume
#   db_volume:
#     name:
#       db-volume

networks:
  inception-network:
    name :
      inception-network
    driver: bridge
