version: '3.9'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
    name: database_volume
    driver: local
    driver_opts:
      type: none
      device: ~/data/database
      o: bind
  webfiles:
    name: webfiles_volume
    driver: local
    driver_opts:
      type: none
      device: ~/data/webfiles
      o: bind

services:
  db:
    container_name: db
    env_file: .env
    build: ./mariadb/
    volumes: 
      - database:/data/database
    configs:
      - source: mariadb_config
        target: etc/my.cnf
    networks:
      - inception
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h" ,"localhost"]
      interval: 5s
      timeout: 2s
      retries: 5

  wpphp:
    container_name: wpphp
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    build: ./wpphp
    volumes:
      - webfiles:/data/webfiles/
    configs:
      - source: wpphp_config
        target: /data/webfiles/wp-config.php
    # ports:
    #   - 9000:9000
    networks:
      - inception
    restart:  on-failure
    # stdin_open: true    # Keep STDIN open even if not attached
    # tty: true           # Allocate a pseudo-TTY

  nginx:
    container_name: nginx
    depends_on:
      wpphp:
        condition: service_started
    build: ./nginx
    volumes:
      - webfiles:/data/webfiles
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    ports:
      - 433:433
    networks:
      - inception
    restart:  on-failure
    # stdin_open: true    # Keep STDIN open even if not attached
    # tty: true           # Allocate a pseudo-TTY


configs:
  mariadb_config:
    file: ./mariadb/mariadb.conf
  nginx_config:
    file: ./nginx/nginx.conf
  wpphp_config:
    file: ./wpphp/wp-config.php
