#TO DO : replace astrid by ageels when on school computer
version: '3.9'

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  database:
    name: database_volume
    driver: local
    driver_opts:
      type: none
      device: ~/data/database
      o: bind
  webfiles:
    name: webfiles_volume
    driver: local
    driver_opts:
      type: none
      device: ~/data/webfiles
      o: bind

services:
  # db:
  #   container_name: db
  #   env_file: .env
  #   build: ./mariadb/
  #   volumes: 
  #     - database:/data/database
  #   configs:
  #     - source: mariadb_config
  #       target: etc/my.cnf
  #   networks:
  #     - inception
  #   restart: on-failure

  # wpphp:
  #   container_name: wpphp
  #   # env_file: .env
  #   depends_on:
  #     - db
  #   build: ./wpphp
  #   volumes:
  #     - webfiles:/var/www/html
  #   # ports:
  #   #   - 9000:9000
  #   networks:
  #     - inception
  #   restart:  on-failure
  #   # stdin_open: true    # Keep STDIN open even if not attached
  #   # tty: true           # Allocate a pseudo-TTY

  nginx:
    container_name: nginx
    # depends_on:
      # - db
      # - wpphp
    build: ./nginx
    volumes:
      - webfiles:/var/www/html
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    ports:
      - 4433:433
    networks:
      - inception
    restart:  on-failure
    # stdin_open: true    # Keep STDIN open even if not attached
    # tty: true           # Allocate a pseudo-TTY


configs:
  mariadb_config:
    file: ./mariadb/mariadb.conf
  nginx_config:
    file: ./nginx/nginx.conf
