version: "3.9"

networks:
  inception:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /Users/astrid/data/mariadb
      o: bind
  webfiles:
    driver: local
    driver_opts:
      type: none
      device: /Users/astrid/data/wordpress
      o: bind

services:
  db_service:
    build: ./mariadb
    init: true
    restart: always
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
    env_file: .env
    networks:
      - inception
    tty : true

  wp_service:
    build: ./wordpress
    init: true
    env_file: .env
    depends_on:
      - db_service
    volumes:
      - webfiles:/var/www/wordpress
    networks:
      - inception
    restart: always

  nginx_service:
    build: ./nginx
    init: true
    env_file: .env
    depends_on:
      - db_service
      - wp_service
    volumes:
      - webfiles:/var/www/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    # tty : true