version: "3.9"

networks:
  inception:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /Users/astrid/data/mariadb
      o: bind
  webfiles:
    driver: local
    driver_opts:
      type: none
      device: /Users/astrid/data/wordpress
      o: bind

services:
  mariadb:
    init: true
    build: ./mariadb
    restart: always
    expose:
      - "3306"
    volumes:
      - database:/var/lib/mysql
    env_file: .env
    networks:
      - inception
    tty : true

  wordpress:
    init: true
    env_file: .env
    depends_on:
      - mariadb
    build: ./wordpress
    volumes:
      - webfiles:/var/www/html/wordpress
    networks:
      - inception
    restart: always

  nginx:
    env_file: .env
    depends_on:
      - wordpress
    build: ./nginx
    volumes:
      - webfiles:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception
    restart: always
    tty : true