version: '3'

networks:
  inception-network:
    name :
      inception-network
    driver: bridge

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - inception-network

  wordpress:
    depends_on:
      - db
    build: ./wordpress
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception-network

  db:
    build: ./mariadb
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception-network

volumes:
  wordpress_volume:
    name:
      wordpress-volume
  db_volume:
    name:
      db-volume

